springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

server:
  port: 8080
  # Spring이 실제 외부 프로토콜은 https 라고 인식하게 함
  forward-headers-strategy: framework

spring:
  application:
    name: stalk-api

  datasource:
#    url: jdbc:h2:mem:stalk;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
    url: jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres.wxtovukiqavynznsumxx
    password: ${SUPABASE_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    # show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

app:
  cors:
    allowed-origins:
      - "http://localhost:5173"
      # 배포된 프론트 도메인도 여기에 추가 (예: https://stalk-front.vercel.app)

kakao:
  oauth:
    client-id: ${KAKAO_CLIENT_ID}
    redirect-uri: ${KAKAO_REDIRECT_URI_DEV}
    frontend-redirect-uri: http://localhost:5173/
#    frontend-redirect-uri: https://s-talk.vercel.app/
    token-uri: https://kauth.kakao.com/oauth/token
    user-uri: https://kapi.kakao.com/v2/user/me

jwt:
  issuer: stalk
  secret: ${JWT_SECRET}
  access-token-seconds: 21600        # 15분
  refresh-token-seconds: 1209600   # 14일

kis:
  base-url: https://openapi.koreainvestment.com:9443  # 실전
  appkey: ${KIS_APPKEY}
  appsecret: ${KIS_APPSECRET}
  custtype: P                 # 개인: P, 법인: B

  token:
    path: /oauth2/tokenP

  domestic:
    # 주식 현재가 조회용
    inquire-price-path: /uapi/domestic-stock/v1/quotations/inquire-price
    tr-id-inquire-price: FHKST01010100

    inquire-index-price-path: /uapi/domestic-stock/v1/quotations/inquire-index-price
    tr-id-inquire-index-price: FHPUP02100000

  overseas:
    inquire-daily-chartprice-path: /uapi/overseas-price/v1/quotations/inquire-daily-chartprice
    tr-id-inquire-daily-chartprice: FHKST03030100

stocks:
  poll:
    fixed-delay-ms: 30000
  watchlist:
    - "000660"  # SK하이닉스
    - "005930"  # 삼성전자
    - "009150"  # 삼성전기
    - "034730"  # SK
    - "005380"  # 현대차
    - "079550"  # LIG넥스원
    - "272210"  # 한화시스템
    - "064350"  # 현대로템
    - "011200"  # HMM
    - "006800"  # 미래에셋증권

market:
  domestic:
    kospi-code: "0001"

  overseas:
    nasdaq-code: "NDX"
    sp500-code: "SPX"
    usd-krw-code: "FX@KRW"

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health # prometheus 엔드포인트 활성화

  prometheus:
    metrics:
      export:
        enabled: true